<a href="https://colab.research.google.com/github/Nikhat24/myprofile/blob/master/iitk_pydata_Nikhat_day03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
np_arr= np.arange(1000000000)
%time z= np_arr*2

CPU times: user 1.67 s, sys: 2.11 ms, total: 1.67 s
Wall time: 1.67 s


In [0]:
%%time 
for i in y:
  i*3

CPU times: user 13 ms, sys: 58 µs, total: 13.1 ms
Wall time: 12.9 ms


In [0]:
[i*2 for i in y]

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [0]:
z=np.random.randn(3,3)    
z

array([[-0.83763217,  0.92863988,  0.55572932],
       [ 1.1808999 , -0.23254816, -1.86970586],
       [ 0.25564005, -0.75631628,  1.18035843]])

In [0]:
z.ndim     #no of dimensions

2

In [0]:
z.shape   #size of each dimensions

(3, 3)

In [0]:
z.dtype    #data type of each value

dtype('float64')

In [0]:
x=np.random.randn(2,4)    #to print a matrix of 2X4 with random values
x


array([[ 0.39733398, -1.30639707, -0.0634597 ,  0.25563042],
       [-0.2801648 ,  0.89688422,  1.47663944, -1.28845949]])

In [0]:
np.ones(((2,3)), dtype=np.int16)    #to print a matrix of 2X4 with 1s

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [0]:
z= np.random.randn(3,4)
np.ones(z.shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
z= np.random.randint(0,2,(2,4))       #to print matrix od 2X4 having 0 n 1 in randomn manner
z

array([[0, 1, 1, 0],
       [1, 0, 0, 1]])

In [0]:
np.random.seed(2)           #to print psuedo-random number in a matrix of 2X5(it will print the same set of values everytime)
z= np.random.randn(2,5)
z

array([[-0.41675785, -0.05626683, -2.1361961 ,  1.64027081, -1.79343559],
       [-0.84174737,  0.50288142, -1.24528809, -1.05795222, -0.90900761]])

In [0]:
arr= np.array([1,2,4])
z= arr.astype(np.float32)
z

array([1., 2., 4.], dtype=float32)

In [0]:
a= np.random.randint(0,6, (4,4))
b= np.random.randint(0,5, (4,4))
a

array([[3, 4, 3, 3],
       [1, 4, 2, 3],
       [0, 0, 2, 5],
       [4, 4, 3, 2]])

In [0]:
b

array([[1, 1, 1, 2],
       [1, 3, 0, 1],
       [0, 4, 3, 1],
       [3, 0, 0, 3]])

In [0]:
a*10

array([[30, 40, 30, 30],
       [10, 40, 20, 30],
       [ 0,  0, 20, 50],
       [40, 40, 30, 20]])

In [0]:
np.dot(a,b)

array([[16, 27, 12, 22],
       [14, 21,  7, 17],
       [15,  8,  6, 17],
       [14, 28, 13, 21]])

In [0]:
a

array([[3, 4, 3, 3],
       [1, 4, 2, 3],
       [0, 0, 2, 5],
       [4, 4, 3, 2]])

In [0]:
b

array([[1, 1, 1, 2],
       [1, 3, 0, 1],
       [0, 4, 3, 1],
       [3, 0, 0, 3]])

In [0]:
np.linalg.det(a)

4.000000000000008

In [0]:
a/3

array([[1.        , 1.33333333, 1.        , 1.        ],
       [0.33333333, 1.33333333, 0.66666667, 1.        ],
       [0.        , 0.        , 0.66666667, 1.66666667],
       [1.33333333, 1.33333333, 1.        , 0.66666667]])

In [0]:
a>2           #elementwise comparison

array([[ True,  True,  True,  True],
       [False,  True, False,  True],
       [False, False, False,  True],
       [ True,  True,  True, False]])

In [0]:
z= np.arange(15) 
z[2:4]= 100   #it will print 100 in 2 n 3 rest all random
z

array([  0,   1, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [0]:
z[:]=300000      #print all values as 3000
z

array([[300000., 300000., 300000., 300000.],
       [300000., 300000., 300000., 300000.],
       [300000., 300000., 300000., 300000.],
       [300000., 300000., 300000., 300000.],
       [300000., 300000., 300000., 300000.],
       [300000., 300000., 300000., 300000.],
       [300000., 300000., 300000., 300000.],
       [300000., 300000., 300000., 300000.]])

In [0]:
z= np.arange(20)
y= z.copy()
z[:]= 1
z
y       #assign value of z to y and then changes all value of z to 1 and y remains teh old z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
w=y[0:20].copy()
w

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
a

array([[3, 4, 3, 3],
       [1, 4, 2, 3],
       [0, 0, 2, 5],
       [4, 4, 3, 2]])

In [0]:
a[:2,1:]      #print row 1 and all column apart from 1

array([[4, 3, 3],
       [4, 2, 3]])

In [0]:
a[2]

array([0, 0, 2, 5])

In [0]:
a[::-1]

array([[4, 4, 3, 2],
       [0, 0, 2, 5],
       [1, 4, 2, 3],
       [3, 4, 3, 3]])

In [0]:
q= np.arange(100)      #to print array of fist 100 numbers in serial order
q

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [0]:
q[::-1]       #reverse of q

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [0]:
z= np.random.rand(8,4)
z

array([[0.66809934, 0.50300677, 0.37800241, 0.33736829],
       [0.95201071, 0.69333383, 0.5341017 , 0.0434897 ],
       [0.24755088, 0.94317072, 0.55686017, 0.35751823],
       [0.00945037, 0.25354827, 0.25422669, 0.17068553],
       [0.34497996, 0.20264905, 0.06290154, 0.0979604 ],
       [0.4967275 , 0.06966059, 0.93515356, 0.20609764],
       [0.46421235, 0.41466826, 0.29133772, 0.32352851],
       [0.21159758, 0.28026829, 0.11710504, 0.68925187]])

In [0]:
z[z>0]
mask = (z>0)&(z>0.4)
z[mask]     #only print the values between 0 n 0.4
#mask         #prints the boolean values for all values of z

array([0.66809934, 0.50300677, 0.95201071, 0.69333383, 0.5341017 ,
       0.94317072, 0.55686017, 0.4967275 , 0.93515356, 0.46421235,
       0.41466826, 0.68925187])

In [0]:
z[[1,2,4,5]]   #prints row 1, 2, 4, 5 rows

array([[0.95201071, 0.69333383, 0.5341017 , 0.0434897 ],
       [0.24755088, 0.94317072, 0.55686017, 0.35751823],
       [0.34497996, 0.20264905, 0.06290154, 0.0979604 ],
       [0.4967275 , 0.06966059, 0.93515356, 0.20609764]])

In [0]:
z[[1,2,4,5],[0,0,0,0]]    #first element of 1, 2, 4, 5

array([0.95201071, 0.24755088, 0.34497996, 0.4967275 ])

In [0]:
v= np.random.randint(0,9, (8,8,8))
v

array([[[0, 0, 6, 0, 8, 6, 1, 2],
        [5, 0, 4, 5, 7, 2, 2, 8],
        [7, 5, 2, 3, 1, 5, 3, 1],
        [0, 7, 6, 5, 8, 0, 7, 1],
        [1, 2, 3, 0, 8, 6, 6, 1],
        [2, 7, 6, 4, 3, 5, 1, 2],
        [3, 7, 3, 5, 4, 4, 1, 4],
        [4, 0, 2, 7, 0, 3, 8, 1]],

       [[6, 2, 4, 3, 6, 4, 4, 2],
        [8, 2, 8, 2, 0, 4, 8, 8],
        [3, 3, 8, 0, 5, 2, 5, 0],
        [3, 5, 2, 5, 2, 1, 8, 8],
        [0, 6, 5, 4, 3, 1, 0, 8],
        [2, 8, 4, 4, 1, 0, 1, 7],
        [4, 7, 5, 4, 4, 7, 5, 1],
        [5, 1, 2, 7, 6, 3, 0, 8]],

       [[6, 1, 5, 5, 5, 3, 7, 7],
        [1, 4, 3, 6, 8, 5, 2, 6],
        [1, 0, 1, 6, 6, 8, 4, 6],
        [6, 1, 5, 7, 0, 4, 7, 5],
        [2, 1, 0, 8, 7, 6, 3, 6],
        [6, 4, 3, 6, 1, 0, 2, 5],
        [8, 8, 3, 1, 6, 1, 8, 8],
        [2, 3, 7, 0, 3, 1, 7, 1]],

       [[5, 5, 3, 3, 3, 4, 8, 0],
        [4, 1, 8, 1, 2, 4, 6, 4],
        [7, 4, 2, 6, 1, 7, 8, 4],
        [2, 6, 6, 4, 3, 0, 0, 5],
        [6, 2, 8, 6, 2, 0, 2, 0],
        

In [0]:
mask = (v>3) & (v<8)
v[mask]= -1*v[mask]
v     #negate the numbers between range 3-8

array([[[ 0,  0, -6,  0,  8, -6,  1,  2],
        [-5,  0, -4, -5, -7,  2,  2,  8],
        [-7, -5,  2,  3,  1, -5,  3,  1],
        [ 0, -7, -6, -5,  8,  0, -7,  1],
        [ 1,  2,  3,  0,  8, -6, -6,  1],
        [ 2, -7, -6, -4,  3, -5,  1,  2],
        [ 3, -7,  3, -5, -4, -4,  1, -4],
        [-4,  0,  2, -7,  0,  3,  8,  1]],

       [[-6,  2, -4,  3, -6, -4, -4,  2],
        [ 8,  2,  8,  2,  0, -4,  8,  8],
        [ 3,  3,  8,  0, -5,  2, -5,  0],
        [ 3, -5,  2, -5,  2,  1,  8,  8],
        [ 0, -6, -5, -4,  3,  1,  0,  8],
        [ 2,  8, -4, -4,  1,  0,  1, -7],
        [-4, -7, -5, -4, -4, -7, -5,  1],
        [-5,  1,  2, -7, -6,  3,  0,  8]],

       [[-6,  1, -5, -5, -5,  3, -7, -7],
        [ 1, -4,  3, -6,  8, -5,  2, -6],
        [ 1,  0,  1, -6, -6,  8, -4, -6],
        [-6,  1, -5, -7,  0, -4, -7, -5],
        [ 2,  1,  0,  8, -7, -6,  3, -6],
        [-6, -4,  3, -6,  1,  0,  2, -5],
        [ 8,  8,  3,  1, -6,  1,  8,  8],
        [ 2,  3, -7,  0,  3,  

In [0]:
a= np.random.randint(0,9, (8,3))
a

array([[1, 6, 1],
       [6, 0, 7],
       [1, 6, 3],
       [0, 0, 0],
       [7, 2, 5],
       [4, 2, 1],
       [3, 0, 5],
       [8, 0, 6]])

In [0]:
b= np.random.randint(0,9, (3,8))
b

array([[3, 0, 7, 6, 3, 7, 2, 8],
       [4, 0, 0, 7, 3, 5, 1, 2],
       [3, 4, 0, 7, 5, 3, 8, 6]])

In [0]:
c=np.dot(a,b)    #product of a n b
c.flatten()      #flatten() converts 2D array into 1D

array([ 30,   4,   7,  55,  26,  40,  16,  26,  39,  28,  42,  85,  53,
        63,  68,  90,  36,  12,   7,  69,  36,  46,  32,  38,   0,   0,
         0,   0,   0,   0,   0,   0,  44,  20,  49,  91,  52,  74,  56,
        90,  23,   4,  28,  45,  23,  41,  18,  42,  24,  20,  21,  53,
        34,  36,  46,  54,  42,  24,  56,  90,  54,  74,  64, 100])

In [0]:
s= np.arange(100)
s.reshape((10,10))
s.reshape(((5,4,5)))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [0]:
c.T

array([[ 30,  39,  36,   0,  44,  23,  24,  42],
       [  4,  28,  12,   0,  20,   4,  20,  24],
       [  7,  42,   7,   0,  49,  28,  21,  56],
       [ 55,  85,  69,   0,  91,  45,  53,  90],
       [ 26,  53,  36,   0,  52,  23,  34,  54],
       [ 40,  63,  46,   0,  74,  41,  36,  74],
       [ 16,  68,  32,   0,  56,  18,  46,  64],
       [ 26,  90,  38,   0,  90,  42,  54, 100]])

In [0]:
p= np.arange(8)
p


array([0, 1, 2, 3, 4, 5, 6, 7])

In [0]:
np.square(p)

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [0]:
np.sqrt(p)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [0]:
np.add(p,p)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [0]:
np.exp(p)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [0]:
np.sign(p)

array([0, 1, 1, 1, 1, 1, 1, 1])

In [0]:
np.isnan(p)

array([False, False, False, False, False, False, False, False])

In [0]:
np.power(p, 3)

array([  0,   1,   8,  27,  64, 125, 216, 343])

In [0]:
np.logical_and(p, p)

array([False,  True,  True,  True,  True,  True,  True,  True])

In [0]:
r=np.random.randn(50,2)
r
o=(r*r).copy()
o
t= np.empty((50), float)
t[:]= o.sum(axis=1)
d= np.argsort(t)
d[40:50]
print(r[d[40:50]])

[[-0.83497014 -1.29325991]
 [ 1.50745343 -0.37804486]
 [ 1.54144273  0.41159065]
 [ 0.99489261  1.24933705]
 [ 1.32882143 -0.92824513]
 [ 1.41095195 -1.23394522]
 [-1.68873201  0.97526641]
 [-0.50670724  2.03094352]
 [ 1.46011547  2.25618456]
 [ 2.88617256 -0.96543075]]


In [0]:
np.random.seed(0)          #print 10 ponts closest to origin from 100 values in an array
points=np.random.randn(100,2)
origin=np.sqrt(np.sum(points*points, axis=1))
points[origin.argsort()][:10]

array([[ 0.04575852, -0.18718385],
       [ 0.06651722,  0.3024719 ],
       [-0.31155253,  0.05616534],
       [-0.34791215,  0.15634897],
       [ 0.15494743,  0.37816252],
       [ 0.12691209,  0.40198936],
       [-0.10321885,  0.4105985 ],
       [-0.02818223,  0.42833187],
       [ 0.17742614, -0.40178094],
       [-0.4555325 ,  0.01747916]])

In [0]:
mask= origin <=1
points[mask].shape
mask

array([False, False, False,  True,  True, False,  True,  True, False,
        True, False, False, False,  True, False,  True, False,  True,
       False,  True, False, False,  True, False, False,  True, False,
        True,  True,  True,  True, False,  True, False,  True,  True,
       False,  True, False,  True, False, False, False, False, False,
       False,  True,  True, False,  True, False, False, False,  True,
       False, False, False,  True,  True, False, False, False,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False])

In [0]:
np.random.seed(0)
points= np.random.uniform(-1, 1, (100,2))
origin= np.sqrt(np.sum(points*points, axis=1))
mask= origin <=1
points[mask].shape[0]

78

In [0]:

g=np.random.randint(5,9, (8,8,8))
g

array([[[7, 8, 6, 6, 8, 7, 7, 8],
        [5, 7, 5, 7, 8, 6, 6, 6],
        [7, 8, 5, 6, 5, 6, 5, 7],
        [7, 5, 7, 5, 7, 7, 5, 6],
        [6, 8, 8, 6, 5, 8, 6, 7],
        [6, 8, 7, 6, 6, 5, 7, 7],
        [7, 6, 6, 8, 5, 8, 5, 8],
        [5, 8, 6, 5, 7, 5, 8, 6]],

       [[5, 7, 7, 7, 6, 7, 5, 8],
        [8, 5, 8, 7, 6, 8, 7, 8],
        [5, 5, 8, 8, 7, 8, 6, 8],
        [5, 6, 8, 7, 8, 5, 5, 5],
        [5, 8, 5, 5, 7, 8, 5, 5],
        [7, 5, 5, 7, 5, 5, 7, 5],
        [7, 5, 8, 8, 5, 8, 8, 8],
        [7, 8, 6, 7, 6, 8, 8, 6]],

       [[5, 8, 7, 6, 6, 8, 6, 6],
        [7, 5, 5, 6, 5, 6, 5, 5],
        [7, 6, 7, 8, 5, 8, 6, 6],
        [6, 8, 8, 6, 6, 8, 6, 5],
        [6, 5, 7, 8, 5, 8, 8, 7],
        [6, 5, 5, 5, 7, 6, 8, 8],
        [5, 8, 7, 5, 5, 5, 5, 7],
        [8, 6, 6, 5, 7, 6, 6, 8]],

       [[5, 8, 8, 5, 7, 8, 6, 5],
        [7, 7, 7, 6, 8, 8, 6, 6],
        [7, 7, 8, 5, 8, 8, 8, 8],
        [5, 6, 8, 6, 5, 6, 5, 5],
        [8, 5, 7, 6, 8, 7, 6, 7],
        

In [0]:
g=np.random.randint(0, 5, (5,5))
h=np.random.randint(0, 5, (5,5))
i=np.dot(g,h)
i



array([[10,  6,  8,  6, 10],
       [30, 27, 20, 18, 31],
       [33, 27, 26, 11, 35],
       [ 6,  3,  1, 14,  3],
       [28, 22, 23, 24, 37]])

In [0]:
np.diag(i)    #print diagonal

array([10, 27, 26, 14, 37])

In [0]:
z= np.random.randint(0,9,(3,3))       #negate boolean value in its own place
z
mask= z>5
mask


array([[ True,  True, False],
       [ True, False, False],
       [False, False, False]])

In [0]:
np.logical_not(mask,mask)

array([[False, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [0]:
arr= np.random.randn(4, 4)
arr

array([[ 0.45659076,  0.11249504,  0.40599608,  1.17448563],
       [ 0.32100233, -0.44059648, -1.76077643,  0.94845643],
       [ 0.75465227,  0.00320806, -0.89705847, -0.35761398],
       [-0.60184032,  0.74221159,  0.79784547, -0.79179744]])

In [0]:
np.where(arr>0, "X8i", "0")

array([['X8i', 'X8i', 'X8i', 'X8i'],
       ['X8i', '0', '0', 'X8i'],
       ['X8i', 'X8i', '0', '0'],
       ['0', 'X8i', 'X8i', '0']], dtype='<U3')

In [0]:
z= np.random.randint(0, 9, (5,5))
z

array([[6, 3, 7, 2, 6],
       [3, 5, 8, 5, 0],
       [6, 1, 4, 7, 5],
       [2, 6, 4, 7, 3],
       [6, 7, 0, 6, 4]])

In [0]:
np.sort(z)

array([[0, 1, 3, 5, 8],
       [1, 1, 6, 7, 8],
       [4, 5, 6, 7, 8],
       [1, 4, 5, 7, 8],
       [0, 7, 7, 7, 8]])

In [0]:
z.sort(0)
z

array([[2, 1, 0, 2, 0],
       [3, 3, 4, 5, 3],
       [6, 5, 4, 6, 4],
       [6, 6, 7, 7, 5],
       [6, 7, 8, 7, 6]])

In [0]:
!pwd

/content


# **Pandas**

In [0]:
import pandas as pd

In [0]:
z= pd.Series([1,2,3,4])
z*2


0    2
1    4
2    6
3    8
dtype: int64

In [0]:
np.exp(z)

0     2.718282
1     7.389056
2    20.085537
3    54.598150
dtype: float64

In [0]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [0]:
z= pd.Series([1.0,2.0], index=[1,2])
z

1    1.0
2    2.0
dtype: float64

In [0]:
s= pd.Series([1.0,2.0], index=[3,4])
s

3    1.0
4    2.0
dtype: float64

In [0]:
pd.Series([1,2,3,'x'], index = ['a','b','c','d'])

a    1
b    2
c    3
d    x
dtype: object

In [0]:
z = pd.Series([1,2,3,4])
z*2

0    2
1    4
2    6
3    8
dtype: int64

In [0]:
z = pd.Series({'b':1,'a':2,'d':3,'c':4}, index = ['a','b','c','d'])
z

a    2
b    1
c    4
d    3
dtype: int64

In [0]:
pd.Series([1,2,3])+pd.Series([1.0,2.0], index = [1,2])

0    NaN
1    3.0
2    5.0
dtype: float64

In [0]:
data = {
   'state':['Ohio','Nevada'],
    'year':[2001,2009]
}
frame = pd.DataFrame(data)
frame

state  year
0    Ohio  2001
1  Nevada  2009

In [0]:
frame['income_cat']=pd.DataFrame([100,200])
frame

state  year  income_cat
0    Ohio  2001         100
1  Nevada  2009         200

In [0]:
del frame['income_cat']
frame

state  year
0    Ohio  2001
1  Nevada  2009

In [0]:
pd.DataFrame(np.random.randn(5,5))

0         1         2         3         4
0 -0.182797  0.701234 -0.610579  0.849227 -1.567303
1  1.844362 -0.839065 -0.400909 -0.914107  2.283512
2  0.546077 -0.921580 -0.889048 -0.071025 -0.240574
3  0.007376 -1.335613 -0.052451  0.319063  1.716086
4  1.611755  0.088389 -0.177068  0.733894  0.867819

In [0]:
x= pd.read_csv("https://bit.ly/2JIORnq", sep="|")
x

user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
5          6   42      M      executive    98101
6          7   57      M  administrator    91344
7          8   36      M  administrator    05201
8          9   29      M        student    01002
9         10   53      M         lawyer    90703
10        11   39      F          other    30329
11        12   28      F          other    06405
12        13   47      M       educator    29206
13        14   45      M      scientist    55106
14        15   49      F       educator    97301
15        16   21      M  entertainment    10309
16        17   30      M     programmer    06355
17        18   35      F          other    37212
18        19   40      M      librarian    02138
19        20   42      F      homemaker    95660
20        21   26      M         writer    30068
21        22   25      M         writer    40206
22        23   30      F         artist    48197
23        24   21      F         artist    94533
24        25   39      M       engineer    55107
25        26   49      M       engineer    21044
26        27   40      F      librarian    30030
27        28   32      M         writer    55369
28        29   41      M     programmer    94043
29        30    7      M        student    55436
..       ...  ...    ...            ...      ...
913      914   44      F          other    08105
914      915   50      M  entertainment    60614
915      916   27      M       engineer    N2L5N
916      917   22      F        student    20006
917      918   40      M      scientist    70116
918      919   25      M          other    14216
919      920   30      F         artist    90008
920      921   20      F        student    98801
921      922   29      F  administrator    21114
922      923   21      M        student    E2E3R
923      924   29      M          other    11753
924      925   18      F       salesman    49036
925      926   49      M  entertainment    01701
926      927   23      M     programmer    55428
927      928   21      M        student    55408
928      929   44      M      scientist    53711
929      930   28      F      scientist    07310
930      931   60      M       educator    33556
931      932   58      M       educator    06437
932      933   28      M        student    48105
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]